### ISSUE TITLE
Wrong keys 'restraint' error while running examples after yank install

### ISSUE THREAD

**Issue by jchus** [choderalab/yank-examples#38]
Installed yank through conda, downloaded the examples from here but got an error (seems to be the same error for all examples)

bash-3.2$ sh run-p-xylene-explicit.sh 
Running simulation...
2016-11-21 10:56:03,252: MPI disabled.
2016-11-21 10:56:03,259: ERROR - yank.yamlbuild - Experiment : Wrong keys 'restraint' in {'restraint': {'type': 'Harmonic'}, 'protocol': 'absolute-binding', 'system': 't4-xylene'}
Traceback (most recent call last):
  File "anaconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.12.0', 'console_scripts', 'yank')()
  File "anaconda/lib/python2.7/site-packages/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "anaconda/lib/python2.7/site-packages/yank/commands/script.py", line 58, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "anaconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1203, in __init__
    self.parse(yaml_source)
  File "anaconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1271, in parse
    self._parse_experiments(yaml_content)
  File "anaconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1829, in _parse_experiments
    raise YamlParseError('Experiment {}: {}'.format(experiment_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: Experiment : Wrong keys 'restraint' in {'restraint': {'type': 'Harmonic'}, 'protocol': 'absolute-binding', 'system': 't4-xylene'}
Analyzing data...
2016-11-21 10:56:05,206: ERROR - yank.analyze - Cannot find analysis.yaml script in p-xylene-explicit-output
Traceback (most recent call last):
  File "anaconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.12.0', 'console_scripts', 'yank')()
  File "anaconda/lib/python2.7/site-packages/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "anaconda/lib/python2.7/site-packages/yank/commands/analyze.py", line 63, in dispatch
    analyze.analyze(args['--store'])
  File "anaconda/lib/python2.7/site-packages/yank/analyze.py", line 442, in analyze
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in p-xylene-explicit-output
bash-3.2$ yank selftest

YANK Selftest
-------------
Yank Version 0.12.0 

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 CUDA
    3 OpenCL

Valid OpenEye install not found
Not required, but please check install if you expected it

YANK Selftest complete.
Thank you for using YANK!

**Comment by Lnaden** [comment]
We recently changed how the `restraint` key was defined in a newer version of YANK and updated the examples to reflect that.

We have not released that version of YANK to conda, but you can build the development version of YANK right now to get that feature by the following: 

1. Uninstall old version of YANK 
1. [the main YANK page](https://github.com/choderalab/yank)
1. Clone the repo
1. `cd` into the repo
1. `conda build devtools/conda-recipe`
1. `conda install --use-local yank-dev`

We're working on critical bugfixes for YANK that have taken a bit to track down but hopefully should have a release this week.

I should have updated the minimum YANK version with the change to the repos however. I'll open an issue for this to make sure this change gets in when we cut the main yank-examples release as well.

**Comment by jchodera** [comment]
`yank` 0.14.1 has now been released:
https://anaconda.org/omnia/yank/files
