### ISSUE TITLE
Get Travis tests running again

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank-examples#60]
We need the travis tests running again to test the examples.

We need a faster minimizer than is currently available to not time out the travis tests. Tests should be able to run at least 1 iteration through the CPU on travis. 

Possible option: split up the yank-examples to run each example as a separate travis job to distribute the workload. We would only run this through 1 version of Python through to avoid having `n_python * n_example` number of jobs (which would be slow to validate, especially as we add more examples)

xref: #59

**Comment by jchodera** [comment]
@lnaden: Any chance we can get travis and nightlies running on this repo? If we skipped minimization and set zero iterations---just for travis---would that at least make sure the input files are still current?

**Comment by Lnaden** [comment]
Probably not too hard. With the `overwrite` function from the cli.

**Comment by jchodera** [comment]
In https://github.com/choderalab/yank-examples/issues/74#issuecomment-341869800 @andrrizzi suggests:
> What if we just use the API and stop right before calling run()? Something like this would test up to (including) `ReplicaExchange.create()`:
```python
# For each example_script
experiment_builder = ExperimentBuilder(example_script)
for experiment in experiment_builder.build_experiments():
    for phase in experiment.phases:
        phase.create_alchemical_phase()
```
I'm also working on GPU travis (we'll talk about that this morning) but this sounds like a good short-term solution!

**Comment by jaimergp** [comment]
Hello! I am trying to run these examples but, at least with my current configuration, none of them can run. The main problem is that `number_of_iterations` is no longer a valid option, but there are some additional problems.

I ran:

```
# I need to use `bash -c` because I am using fish as the main shell.
find . -name '*.yaml' -exec bash -c "echo '{}' && timeout 10 yank script --yaml={}" \;
```

<details><summary>Output</summary>
<p>

```
./hydration/phenol/explicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./hydration/phenol/implicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./hydration/freesolv/yank.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./binding/abl-imatinib/explicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter timestep, number_of_iterations, nsteps_per_iteration
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter timestep, number_of_iterations, nsteps_per_iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter timestep, number_of_iterations, nsteps_per_iteration

***********************************************************************************************************

./binding/abl-imatinib/implicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations, timestep, nsteps_per_iteration
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations, timestep, nsteps_per_iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations, timestep, nsteps_per_iteration

***********************************************************************************************************

./binding/host-guest/yank.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./binding/t4-lysozyme/all-ligands-implicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./binding/t4-lysozyme/p-xylene-implicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./binding/t4-lysozyme/p-xylene-explicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

***********************************************************************************************************

./binding/t4-lysozyme/all-ligands-explicit.yaml
/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py:1168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1229, in _validate_options
    special_conversions=special_conversions)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/utils.py", line 1060, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaime/.local/anaconda/envs/openforcefield/bin/yank", line 11, in <module>
    load_entry_point('yank==0.24.0', 'console_scripts', 'yank')()
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/commands/script.py", line 145, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 639, in __init__
    self.parse(script)
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 729, in parse
    validate_general_options=True))
  File "/home/jaime/.local/anaconda/envs/openforcefield/lib/python3.7/site-packages/yank/experiment.py", line 1231, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

```
</p>
</details>

Configuration:

```
$ yank --version
0.24.0.dev0
$ python -V
Python 3.7.3
$ conda list yank-examples
# packages in environment at /home/jaime/.local/anaconda/envs/openforcefield:
#
# Name                    Version                   Build  Channel
yank-examples             1.1.0                         0    omnia
```

**Comment by jchodera** [comment]
The YAML syntax has changed. @andrrizzi will have to help you go through these and update the YAML syntax.

**Comment by jaimergp** [comment]
Nice. Regarding timeouts in Travis, [Azure Pipelines](https://github.com/marketplace/azure-pipelines) could be a solution, since they don't have a time limit. `conda-smithy` [has some templates](https://github.com/conda-forge/conda-smithy/tree/master/conda_smithy/templates).

**Comment by jaimergp** [comment]
Hm, maybe not _unlimited_ time, but [quite generous](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#public-github-repository-and-azure-pipelines-in-a-public-project):

> If both your GitHub repository and your pipeline are public, you can run up to 10 parallel jobs in Azure Pipelines for free. These free jobs have a maximum timeout of 360 minutes (6 hours) each. If you need more, you can contact us to have the limits increased.

**Comment by andrrizzi** [comment]
> `yank.experiment.YamlParseError: found unknown parameter number_of_iterations, timestep, nsteps_per_iteration`

I think all three of these should be changed to `default_number_of_iterations`, `default_timestep`, `default_nsteps_per_iteration`.
