### ISSUE TITLE
Set resume_setup: yes in all of these examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank-examples#70]
Is there any reason to have this crash otherwise with the error message
```
Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/experiment.py", line 716, in run_experiments
    self._setup_experiments()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/experiment.py", line 1790, in _setup_experiments
    self._db.setup_all_systems()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/pipeline.py", line 1044, in setup_all_systems
    group_nodes=1, sync_nodes=True)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/mpi.py", line 388, in distribute
    results.append(task(distributed_arg, *other_args, **kwargs))
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/pipeline.py", line 1124, in _setup_molecules
    os.makedirs(mol_dir)
  File "/home/chodera/miniconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'explicit/setup/molecules/STI_2'
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
each time you rerun it?

**Comment by jchodera** [comment]
Until we have a better error message when refusing to resume, it's a good idea to set this.

**Comment by Lnaden** [comment]
This error is not related to the `resume_setup` flag, this is actually a problem with the parallel setup from choderalab/yank#808 I linked above.
