### ISSUE TITLE
Enable automated testing of examples; validate examples actually run

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank-examples#74]
I'm attempting to run the hydration example on a fresh conda install of Yank on my Mac, and get this error:
```
2017-11-03 16:20:21,963: ERROR - yank.experiment - Molecule binders: is_peptide('freesolv-mini.smiles') should evaluate to True
Traceback (most recent call last):
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1119, in _validate_molecules
    validated_molecules[molecule_id] = molecule_schema.validate(molecule_descr)
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/schema-0.6.2-py3.6.egg/schema.py", line 74, in validate
schema.SchemaError: Or({'smiles': <class 'str'>, Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x127551840>), [<class 'str'>])}, Optional('openeye'): {'quacpac': 'am1-bcc'}, Optional('antechamber'): {'charge_method': Or(<class 'str'>, None)}, Optional('epik'): {Optional('max_structures'): <class 'int'>, Optional('ph'): <class 'float'>, Optional('ph_tolerance'): <class 'object'>, Optional('min_probability'): <class 'object'>, Optional('tautomerize'): <class 'bool'>, Optional('max_atoms'): <class 'int'>, 'select': <class 'int'>}}, {'name': <class 'str'>, Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x127551840>), [<class 'str'>])}, Optional('openeye'): {'quacpac': 'am1-bcc'}, Optional('antechamber'): {'charge_method': Or(<class 'str'>, None)}, Optional('epik'): {Optional('max_structures'): <class 'int'>, Optional('ph'): <class 'float'>, Optional('ph_tolerance'): <class 'object'>, Optional('min_probability'): <class 'object'>, Optional('tautomerize'): <class 'bool'>, Optional('max_atoms'): <class 'int'>, 'select': <class 'int'>}}, {'filepath': <function ExperimentBuilder._validate_molecules.<locals>.is_small_molecule at 0x1275b7598>, Optional('select'): Or(<class 'int'>, 'all'), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x127551840>), [<class 'str'>])}, Optional('openeye'): {'quacpac': 'am1-bcc'}, Optional('antechamber'): {'charge_method': Or(<class 'str'>, None)}, Optional('epik'): {Optional('max_structures'): <class 'int'>, Optional('ph'): <class 'float'>, Optional('ph_tolerance'): <class 'object'>, Optional('min_probability'): <class 'object'>, Optional('tautomerize'): <class 'bool'>, Optional('max_atoms'): <class 'int'>, 'select': <class 'int'>}}, {'filepath': <function ExperimentBuilder._validate_molecules.<locals>.is_peptide at 0x11056bae8>, Optional('select'): Or(<class 'int'>, 'all'), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x127551840>), [<class 'str'>])}, Optional('strip_protons'): <class 'bool'>}) did not validate {'filepath': 'freesolv-mini.smiles', 'antechamber': {'charge_method': 'bcc'}, 'select': 'all1'}
is_peptide('freesolv-mini.smiles') should evaluate to True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dmobley/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/commands/script.py", line 110, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 580, in __init__
    self.parse(script)
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 691, in parse
    self._db.molecules = self._validate_molecules(yaml_content.get('molecules', {}))
  File "/Users/dmobley/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1140, in _validate_molecules
    raise YamlParseError('Molecule {}: {}'.format(molecule_id, e.autos[-1]))
yank.experiment.YamlParseError: Molecule binders: is_peptide('freesolv-mini.smiles') should evaluate to True
```
Tips? I also ran into the same issue on trying to run Yank on my own molecule (mol2 file from FreeSolv) with my own Yaml, so I backed off to trying to get the example to work, but it has the same issue.

**Comment by davidlmobley** [comment]
@jchodera , tips? I'm trying to prepare a tutorial on doing hydration calculations with Yank, but, well, so far no good.

**Comment by jchodera** [comment]
Let me see if I can reproduce this.

**Comment by andrrizzi** [comment]
There's a typo in `select` here
```yaml
molecules:
  binders:
    # .smiles files are treated the same as .cvs files
    filepath: freesolv-mini.smiles
    antechamber:
      charge_method: bcc
    select: all1
```
Try removing the `1` after `all`.

**Comment by jchodera** [comment]
@lnaden: We really need to get an automated test script that tests these examples on travis (as well as our own cluster). They're useless if they don't run.

**Comment by davidlmobley** [comment]
I can verify that the example now runs with @andrrizzi 's fix. But now I have to sort out why the case I was working on fails (it does not have this typo and raises a very similar exception).

It would be nice if the raised exception was slightly more informative. It sounded like it was having some sort of problem processing my "peptide" (small molecules).

**Comment by andrrizzi** [comment]
I think the automatic tests are coming along in #68 .

> It would be nice if the raised exception was slightly more informative.

I know, sorry about that. This is a much harder problem that you would think because the supported syntax is so flexible. You can raise an issue on yank with the script and the error. I'll be happy to help out.

**Comment by davidlmobley** [comment]
Ah, I seem to have found that specific issue. It seems I had specified the filename incorrectly, which resulted in this exception:
```    raise YamlParseError('Molecule {}: {}'.format(molecule_id, e.autos[-1]))
yank.experiment.YamlParseError: Molecule input_molecule: is_peptide('output_dir/input.mol2') raised TypeError("__init__() missing 1 required positional argument: 'errors'",)
```
This is not super helpful as it sounds like it's a problem with the type of my input molecule rather than a problem with whether the file exists.

**Comment by jchodera** [comment]
We've been struggling with a better way to give helpful failure error messages, but it's very difficult to do so while still supporting a flexible and extensible input schema. 

@andrrizzi : What if we required the user to explicit state what format they are providing via a `format` keyword? That would let us provide much more useful error messages, since we could route the schema dispatch based on the user-supplied keyword. This isn't as awesome as the flexible system you've engineered, but would be simple to add and maybe much more user-friendly.

For example, instead of just
```yaml
molecules:
  binders:
    # .smiles files are treated the same as .cvs files
    filepath: freesolv-mini.smiles
    antechamber:
      charge_method: bcc
    select: all
```
we'd have
```yaml
molecules:
  binders:
    # .smiles files are treated the same as .cvs files
    filepath: freesolv-mini.smiles
    format: smiles
    antechamber:
      charge_method: bcc
    select: all
```
and instead of
```yaml
molecules:
  Abl:
    filepath: input/2HYY-pdbfixer.pdb
  STI:
    filepath: input/STI02.mol2
    epik:
      select: !Combinatorial [0, 1, 2]
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null
```
we'd have
```yaml
molecules:
  Abl:
    filepath: input/2HYY-pdbfixer.pdb
    format: pdb
  STI:
    filepath: input/STI02.mol2
    format: mol2
    epik:
      select: !Combinatorial [0, 1, 2]
      ph: 7.4
      ph_tolerance: 7.0
      tautomerize: no
    openeye:
      quacpac: am1-bcc
    antechamber:
      charge_method: null
```

**Comment by Lnaden** [comment]
@jchodera I have been trying to do that in #68, but the problem is the initial energy evaluation, which must be done even with 0 iterations, is so slow on travis that even trying 1 test times out. I don't have any ideas for a fix, I can try to reduce the number of states to 2 for the travis tests, but I'm not even sure that will be fast enough to not time out.

**Comment by jchodera** [comment]
Could we skip the initial energy evaluation during initial setup and record a special value (zero, inf, or nan) in the matrix or set a flag to ensure this is done when the simulation actually starts?

**Comment by jchodera** [comment]
Or is the `System` construction the slow part, rather than the energy computation?

**Comment by Lnaden** [comment]
Its the initial energy evaluation, its not skippable unless we manually step through each action by hand, and even then, I'm not sure we can skip the initial energy as I'm pretty sure its part of repex initialization. But its a function of the number of states, so I can try reducing the number of states for the test.

We need to be careful though, because if I wind up overriding too many options, then its not a very good test of the example as it stands.

**Comment by jchodera** [comment]
I'd be pretty happy if we could at least make sure the examples weren't full of syntax errors that triggered cryptic error messages. That's the quickest way to turn off any potential users and ensure nobody will ever fund code development.

**Comment by jchodera** [comment]
If this means restructuring the startup logic, I think we should restructure the startup logic if there is no other way to avoid this. We might be able to get GPu travis running, however, so I'll give that a try first.

**Comment by andrrizzi** [comment]
> What if we required the user to explicit state what format they are providing via a format keyword?

I don't think that's a problem here. We can always read the extension to understand the format. To give you an example of the core problem: We don't allow `epik` to be run on proteins. If the user writes this
```yaml
molecules:
  my-molecule:
    filepath: myprotein.pdb
    epik:
      select: 0
```
which error do we raise? Did the user wanted to specify a file including a small molecule or did they requested epik by mistake?

This is a simple example to give you an idea, but there are a whole number of exclusive schemas for which it's unclear what the user intended to do, and we haven't found a solution yet that doesn't involve parsing everything with a huge `if...else` list.

> Its the initial energy evaluation, its not skippable unless we manually step through each action by hand, and even then, I'm not sure we can skip the initial energy as I'm pretty sure its part of repex initialization. 

What if we just use the API and stop right before calling `run()`? Something like this would test up to (including) `ReplicaExchange.create()`

```python
# For each example_script
experiment_builder = ExperimentBuilder(example_script)
for experiment in experiment_builder.build_experiments():
    for phase in experiment.phases:
        phase.create_alchemical_phase()
```

**Comment by jchodera** [comment]
> What if we just use the API and stop right before calling run()? Something like this would test up to (including) ReplicaExchange.create()

That's a great idea! It would at least make sure the input files are all parseable.

**Comment by jchodera** [comment]
> which error do we raise? Did the user wanted to specify a file including a small molecule or did they requested epik by mistake?

I think anything human-intelligible would be a huge step forward toward usability. For example, if there error there was
```
Error: Epik cannot be run on proteins. 

You specified:

molecules:
  my-molecule:
    filepath: myprotein.pdb
    epik:
      select: 0

Either specify a valid small molecule input format or omit the "epik" block.
```
this is something nobody would argue was uninformative. There may be a way that we can add some minimal kinds of error checking that wouldn't be a huge nested `if...else...else` block but still would add intelligent error handling to many common cases. (This is another reason it would be useful to have a remote instrumentation library aggregate information on commonly encountered exceptions!)

**Comment by Lnaden** [comment]
@andrrizzi and I have actually thought about this a little [in an open YANK issue](https://github.com/choderalab/yank/issues/795), we spoke about this in person and figured we would effectively have to extend/re-write the `Schema` validation package to do what we want. We made it lower priority because of the work that would need to go into it, which would detract from features and higher priority bug fixes (e.g. NaN's). But we can re-prioritize if we think it would be worth it

**Comment by jchodera** [comment]
I think the rough priority should be:
1. The software should be easy to install
2. The software should run the examples without throwing a syntax error
3. The software should run the examples without crashing
4. The software should produce valid results when running to completion
5. The software should be usable and produce human-readable error messages when something goes wrong

Right now, we're somewhere around step 1, so let's tackle these in order of priority but think about how to make it easy to eventually get to step 5.
