### ISSUE TITLE
t4-lysozyme analyze error

### ISSUE THREAD

**Issue by 9527567** [choderalab/yank-examples#90]
What an exciting project！
When I run the `examples/binding/t4-lysozyme` case, the simulation ends correctly, but an error is reported during analysis. I didn't change any of the parameters in the example. What should I do to perform the analysis correctly?

$ yank analyze --store=p-xylene-explicit-output/experiments/
`
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/zhangzw/.app/amber20/miniconda/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/analyze.py", line 299, in __init__
    analysis = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x2b6e12b44310>
Traceback (most recent call last):
  File "/home/zhangzw/.app/amber20/miniconda/lib/python3.9/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'`

Here is the automatically generated analyze yaml

![image](https://user-images.githubusercontent.com/50236967/147307413-885542c4-625e-4308-ab0a-852ef2b72c96.png)

Have a nice day!

**Comment by cmielke-vir** [comment]
Ive run into the same problem, but found this issue here. I take it the YAML parser was patched for security issues? : 
https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col

Following their advice, I modified the following file : 
yank/lib/python3.9/site-packages/yank/analyze.py

Replace yaml.load(f) with yaml.safe_load(f)

Now the command runs, but I have no idea if the values are correct :)

Free energy of binding  :   -47.858 +- 0.211 kT (-28.531 +- 0.126 kcal/mol)
DeltaG complex          :    55.460 +- 0.211 kT
DeltaG standard state correction:              0.297 kT
DeltaG solvent          :     7.899 +- 0.001 kT

Enthalpy of binding     :    -8.211 +- 7.502 kT (-4.895 +- 4.472 kcal/mol)

**Comment by 9527567** [comment]
Thank you for your reply. I'm trying.

**Comment by spadavec** [comment]
This is far too late, but for people coming across this recently, it appears that the actual problem is that the `--store` option needs to be adjusted to: 

```bash
yank analyze --store=p-xylene-explicit-explicit-output/experiments
```
